from logger import logger


def query_chain(chain,user_input:str):
    """
    Process the user input through the query chain and return the response.
    
    Args:
        chain: The query processing chain.
        user_input (str): The input query from the user.
        
    Returns:
        str: The response generated by the query chain.
    """
    try:
        logger.debug(f"Processing user input: {user_input}")
        result = chain({"query": user_input})
        response={
            "response":result["result"],
            "sources":[doc.metadata.get("sources","") for doc in result["source_documents"] ]
        }
        logger.debug(f"Chain response: {response}")
        return response
    except Exception as e:
        logger.error(f"Error processing query: {e}")
        raise e